# Generated by Django 4.2.4 on 2025-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsapp', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ImageField(upload_to=''),
        ),
    ]
